#!/usr/bin/env python3
"""Save all 10 analyzed memos to the memos directory and update index/manifest."""
import json
from pathlib import Path
from datetime import datetime
from zoneinfo import ZoneInfo

PACIFIC  = ZoneInfo("America/Los_Angeles")
DATA_DIR = Path.home() / "IPO_Screener" / "memos"
RUN_DATE = "2026-02-26"
DATE_DIR = DATA_DIR / RUN_DATE
DATE_DIR.mkdir(parents=True, exist_ok=True)

def slug(name):
    return "".join(c if c.isalnum() else "_" for c in name.lower())[:40]

def fix_scores(m):
    """Normalize scores to 0-10 scale and recalculate weighted_total on 0-100 scale."""
    s = m.get("scores", {})
    def get(k): return s.get(k) or 0
    def norm(v): return round(v / 10, 1) if v > 10 else v

    bm = norm(get("business_model_quality"))
    fh = norm(get("financial_health_runway"))
    mc = norm(get("market_competitive_position"))
    mg = norm(get("management_governance"))
    va = norm(get("valuation_attractiveness"))

    wt = round(bm * 2.5 + fh * 2.5 + mc * 2.0 + mg * 1.5 + va * 1.5, 1)

    m["scores"] = {
        "business_model_quality":      bm,
        "financial_health_runway":     fh,
        "market_competitive_position": mc,
        "management_governance":       mg,
        "valuation_attractiveness":    va,
        "weighted_total":              wt,
    }
    return m

MEMOS = [

# ── 1. LANTICS CORP ──────────────────────────────────────────────────────────
{
  "company_name": "Lantics Corp.",
  "proposed_ticker": None,
  "exchange": "OTC",
  "sector": "Software & Services",
  "subsector": "Application Software",
  "offering_size_usd_millions": 0.12,
  "offering_shares_millions": 6.0,
  "proposed_price_range": "$0.02 per share",
  "lead_underwriters": [],
  "underwriter_tier": "Self-Underwritten",
  "ipo_type": "Direct",
  "filing_date": "2026-02-24",
  "filing_url": "https://www.sec.gov/Archives/edgar/data/2112585/000168316826001279/0001683168-26-001279-index.htm",
  "auditor": "Qi CPA LLC",
  "auditor_flag": True,
  "financials": {
    "revenue_usd_millions": {"year_minus_2": None, "year_minus_1": None, "ttm": 0.0},
    "revenue_growth_yoy_pct": None, "gross_margin_pct": None, "gross_margin_trend": "",
    "ebitda_usd_millions": None, "net_income_usd_millions": -0.012,
    "cash_burn_quarterly_usd_millions": None, "cash_on_hand_pre_ipo_usd_millions": 0.007,
    "estimated_runway_months_post_ipo": 1.0, "total_debt_usd_millions": 0.0,
    "stock_based_comp_pct_revenue": None, "rule_of_40_score": None,
    "nrr_pct": None, "cac_ltv_ratio": None,
    "ar_vs_revenue_growth_flag": False, "deferred_revenue_trend": "",
  },
  "ownership": {
    "secondary_shares_pct_offering": 0.0, "founder_post_ipo_voting_control_pct": 29.0,
    "dual_class_structure": False, "lock_up_days": None,
    "lock_up_flag": False, "insider_selling_flag": False,
  },
  "use_of_proceeds": {
    "growth_capital_pct": 40.0, "debt_repayment_pct": 0.0,
    "insider_liquidity_pct": 0.0, "general_corporate_pct": 60.0, "proceeds_flag": False,
  },
  "management": {
    "ceo_name": "Usman Kuso", "ceo_tenure_months": 5,
    "cfo_name": None, "cfo_tenure_months": None, "board_independent_pct": 0.0,
    "management_flags": ["Single officer/director manages entire company part-time",
                         "No prior public company experience", "No employees",
                         "Management based in Nigeria — US judgments unenforceable"],
  },
  "valuation": {
    "implied_ev_usd_millions": 0.17, "ev_revenue_multiple": None,
    "sector_median_ev_revenue": None, "premium_to_sector_median_pct": None,
    "public_comps": [], "valuation_flag": True,
  },
  "red_flags": [
    "RF-01 GOING CONCERN — Qi CPA LLC issued substantial doubt on ability to continue as going concern",
    "RF-05 RUNWAY RISK — $6,765 cash on hand; ~$1,600/mo burn; sub-1-month runway pre-IPO; ~8 months post max raise",
    "RF-08 MANAGEMENT RED FLAGS — CEO 5 months tenure; no public company experience; part-time; sole person",
    "RF-10 AUDIT ISSUES — Non-Big 4 unrecognized auditor (Qi CPA LLC) issued going concern opinion",
    "RF-11 MARGIN RISK — Zero revenue; no margin calculable; no path to positive margins articulated",
    "RF-14 CAPITAL STRUCTURE RISK — Negative shareholders equity (-$11,689); liabilities ($60,854) exceed assets ($49,165)",
    "RF-16 GEOGRAPHIC CONCENTRATION — All operations and management in Nigeria; US judgments unenforceable",
    "RF-18 WORKING CAPITAL STRESS — Current ratio < 1.0; net shareholder deficit; balance sheet insolvent",
  ],
  "red_flag_count": 8, "going_concern": True,
  "scores": {"business_model_quality": 2, "financial_health_runway": 1,
              "market_competitive_position": 2, "management_governance": 1,
              "valuation_attractiveness": 1, "weighted_total": None},
  "recommendation": "PASS", "conditions": [],
  "pass_reasons": [
    "RF-01 Going concern — automatic PASS", "Zero revenue since inception (Oct 2025)",
    "Negative shareholders equity (-$11,689)", "Sub-one-month cash runway pre-IPO",
    "Self-underwritten penny stock ($0.02/share, max raise $120k)",
    "Single part-time director with no public company experience",
  ],
  "executive_summary": "Lantics Corp. is a development-stage AI document platform incorporated Oct 2025, operated from Abuja, Nigeria. Zero revenue, negative shareholders deficit of ($11,689), and $6,765 cash. Auditor (Qi CPA LLC) issued going concern. Self-underwritten at $0.02/share targeting max $120,000 raise. Single part-time director, no employees, no revenue traction, operations in a jurisdiction where US judgments are unenforceable. Automatic PASS.",
  "business_overview": "Cloud-based document generation and AI-assisted review platform. Software acquired from Infora Limited (Gibraltar) for $42,400 in Nov 2025. Revenue model: individual subscriptions ($65-90/mo), multi-user ($200-500/mo), enterprise ($1,000-2,600/mo). Zero users disclosed. TAM claim unsourced. Competes against Microsoft Copilot, Google Workspace AI, DocuSign.",
  "key_risks": ["Going concern from auditor", "Negative equity and balance sheet insolvency",
                 "Sub-one-month cash runway", "Zero revenue, no validated user base",
                 "Sole officer part-time, extreme key-man risk",
                 "All operations in Nigeria — legal enforcement impossible",
                 "Penny stock, no underwriter", "Hypercompetitive market with no differentiation"],
  "related_party_flags": ["CEO Usman Kuso receives $1,600/month consulting fee",
                           "Office space provided rent-free by CEO (~$700/month imputed value)",
                           "Software acquired from Infora Limited (Gibraltar) — relationship to CEO not disclosed"],
  "macro_sector_context": "AI document management growing (~$14.7B TAM by 2030) but dominated by Microsoft, Google, DocuSign. No evidence of technical, cost, or distribution advantage for Lantics.",
  "deal_committee_narrative": "Automatic PASS. Going concern, negative equity, sub-month runway, zero revenue, self-underwritten penny stock. Document and decline.",
  "is_amendment": False, "prior_memo_date": None, "amendment_changes_summary": None,
  "accession_no": "0001683168-26-001279",
},

# ── 2. INFLECTION POINT ACQUISITION CORP. VI ──────────────────────────────────
{
  "company_name": "Inflection Point Acquisition Corp. VI",
  "proposed_ticker": None, "exchange": "Nasdaq Global Market",
  "sector": "SPAC", "subsector": "Blank Check Company",
  "offering_size_usd_millions": 220.0, "offering_shares_millions": 22.0,
  "proposed_price_range": "$10.00 per unit",
  "lead_underwriters": ["Cantor Fitzgerald & Co."],
  "underwriter_tier": "Mid-tier", "ipo_type": "SPAC IPO",
  "filing_date": "2026-02-25",
  "filing_url": "https://www.sec.gov/Archives/edgar/data/2102041/000121390026020579/0001213900-26-020579-index.htm",
  "auditor": "BDO USA, P.C.", "auditor_flag": False,
  "financials": {
    "revenue_usd_millions": {"year_minus_2": None, "year_minus_1": None, "ttm": None},
    "revenue_growth_yoy_pct": None, "gross_margin_pct": None, "gross_margin_trend": "",
    "ebitda_usd_millions": None, "net_income_usd_millions": None,
    "cash_burn_quarterly_usd_millions": None, "cash_on_hand_pre_ipo_usd_millions": 2.25,
    "estimated_runway_months_post_ipo": None, "total_debt_usd_millions": None,
    "stock_based_comp_pct_revenue": None, "rule_of_40_score": None,
    "nrr_pct": None, "cac_ltv_ratio": None,
    "ar_vs_revenue_growth_flag": False, "deferred_revenue_trend": "",
  },
  "ownership": {
    "secondary_shares_pct_offering": 0.0, "founder_post_ipo_voting_control_pct": 32.7,
    "dual_class_structure": True, "lock_up_days": 180,
    "lock_up_flag": True, "insider_selling_flag": False,
  },
  "use_of_proceeds": {
    "growth_capital_pct": None, "debt_repayment_pct": None,
    "insider_liquidity_pct": 0.0, "general_corporate_pct": 100.0, "proceeds_flag": False,
  },
  "management": {
    "ceo_name": None, "ceo_tenure_months": None,
    "cfo_name": None, "cfo_tenure_months": None, "board_independent_pct": None,
    "management_flags": ["No specific business combination identified",
                         "Sponsor controls 32.7% of voting rights post-IPO",
                         "$29,167/month admin services fee from day 1"],
  },
  "valuation": {
    "implied_ev_usd_millions": 220.0, "ev_revenue_multiple": None,
    "sector_median_ev_revenue": None, "premium_to_sector_median_pct": None,
    "public_comps": [], "valuation_flag": False,
  },
  "red_flags": [
    "RF-04 INSIDER LIQUIDITY — Sponsor acquired 8.4M founder shares for $25K; massive upside vs public",
    "RF-05 RUNWAY RISK — $29,167/month admin fee; only $2.25M working capital outside trust",
    "RF-06 GOVERNANCE RISK — Sponsor 32.7% post-IPO voting control; dual class; waived redemption rights",
    "RF-13 MARKET TIMING RISK — SPAC market mixed post-2021; no identified target or sector focus",
    "RF-14 CAPITAL STRUCTURE RISK — $9.9M deferred underwriting (4.5% of gross) payable only on BC close",
  ],
  "red_flag_count": 5, "going_concern": False,
  "scores": {"business_model_quality": 2, "financial_health_runway": 2,
              "market_competitive_position": 0, "management_governance": 3,
              "valuation_attractiveness": 3, "weighted_total": None},
  "recommendation": "PASS", "conditions": [],
  "pass_reasons": ["Blank check company — no business to evaluate",
                   "No identified target or sector",
                   "Score of 19/100 well below CONDITIONAL threshold",
                   "Sponsor economics heavily favor insiders over public shareholders"],
  "executive_summary": "Inflection Point Acquisition Corp. VI is a $220M SPAC raising 22M units at $10 via Cantor Fitzgerald. No identified target. Sponsor receives 8.4M founder shares for $25K (32.7% post-IPO). $9.9M deferred underwriting (4.5%) payable only on BC close. $29,167/month admin fee drains the $2.25M working capital in ~77 months. PASS — no investable business.",
  "business_overview": "Blank check company incorporated July 24, 2025. No operations. 24-month window to complete business combination. All $220M in trust. No sector or target disclosed.",
  "key_risks": ["No identified target — binary outcome (acquisition or liquidation)",
                 "Redemption dilution at business combination vote",
                 "24-month deadline — pressure to close any deal",
                 "Sponsor conflict — $25K for 32.7% stake creates misaligned incentives",
                 "Admin fee depletes working capital",
                 "$9.9M deferred commission reduces net proceeds to target"],
  "related_party_flags": ["Sponsor (Inflection Point Holdings VI LLC): 8.4M founder shares for $25K",
                           "IPAM receives $29,167/month admin fee",
                           "Cantor Fitzgerald receives 2.4M placement warrants at $1.00",
                           "IPF LP provides up to $300K interest-free bridge loans"],
  "macro_sector_context": "SPAC market remains active but faces investor scrutiny on sponsor economics, redemption dilution, and deal quality. Cantor Fitzgerald has SPAC credibility but no sector thesis disclosed.",
  "deal_committee_narrative": "Classic SPAC with no differentiation. No target, no sector, $25K sponsor for 32.7% stake. PASS pending any target visibility.",
  "is_amendment": True, "prior_memo_date": None,
  "amendment_changes_summary": "Amendment to original S-1. Updated underwriting agreement, capitalization table, and management disclosures per SEC comment letters. Core deal economics unchanged.",
  "accession_no": "0001213900-26-020579",
},

# ── 3. BHAV ACQUISITION CORP ─────────────────────────────────────────────────
{
  "company_name": "BHAV Acquisition Corp",
  "proposed_ticker": "BHAV", "exchange": "Nasdaq",
  "sector": "SPAC", "subsector": "Blank Check Company",
  "offering_size_usd_millions": 100.0, "offering_shares_millions": 10.0,
  "proposed_price_range": "$10.00 per unit",
  "lead_underwriters": ["Maxim Group LLC"],
  "underwriter_tier": "Tier 2", "ipo_type": "SPAC IPO",
  "filing_date": "2026-02-25",
  "filing_url": "https://www.sec.gov/Archives/edgar/data/2097288/000121390026020436/0001213900-26-020436-index.htm",
  "auditor": "WithumSmith+Brown, PC", "auditor_flag": False,
  "financials": {
    "revenue_usd_millions": {"year_minus_2": None, "year_minus_1": None, "ttm": None},
    "revenue_growth_yoy_pct": None, "gross_margin_pct": None, "gross_margin_trend": "",
    "ebitda_usd_millions": None, "net_income_usd_millions": None,
    "cash_burn_quarterly_usd_millions": None, "cash_on_hand_pre_ipo_usd_millions": 0.75,
    "estimated_runway_months_post_ipo": None, "total_debt_usd_millions": 0.0,
    "stock_based_comp_pct_revenue": None, "rule_of_40_score": None,
    "nrr_pct": None, "cac_ltv_ratio": None,
    "ar_vs_revenue_growth_flag": False, "deferred_revenue_trend": "",
  },
  "ownership": {
    "secondary_shares_pct_offering": 0.0, "founder_post_ipo_voting_control_pct": None,
    "dual_class_structure": True, "lock_up_days": 180,
    "lock_up_flag": True, "insider_selling_flag": False,
  },
  "use_of_proceeds": {
    "growth_capital_pct": 100.0, "debt_repayment_pct": 0.0,
    "insider_liquidity_pct": 0.0, "general_corporate_pct": 0.0, "proceeds_flag": True,
  },
  "management": {
    "ceo_name": None, "ceo_tenure_months": None,
    "cfo_name": None, "cfo_tenure_months": None, "board_independent_pct": None,
    "management_flags": ["No identified target business",
                         "Sponsor (BHAV Partners LLC) acquired 3.2M founder shares for $25K",
                         "$20K/month admin services agreement with Sponsor"],
  },
  "valuation": {
    "implied_ev_usd_millions": 100.0, "ev_revenue_multiple": None,
    "sector_median_ev_revenue": None, "premium_to_sector_median_pct": None,
    "public_comps": [], "valuation_flag": False,
  },
  "red_flags": [
    "RF-04 INSIDER LIQUIDITY — Sponsor (BHAV Partners LLC) acquired 3.2M founder shares for $25K",
    "RF-05 RUNWAY RISK — Only $750K working capital outside trust; $20K/month admin fee",
    "RF-06 GOVERNANCE RISK — Dual class; founder shares lock-up 180 days post-BC",
    "RF-13 MARKET TIMING RISK — No identified target; blank pool with 24-month window",
    "RF-14 CAPITAL STRUCTURE RISK — Redemption dilution risk at BC vote unquantified",
  ],
  "red_flag_count": 5, "going_concern": False,
  "scores": {"business_model_quality": 0, "financial_health_runway": 3,
              "market_competitive_position": 0, "management_governance": 4,
              "valuation_attractiveness": 3, "weighted_total": None},
  "recommendation": "PASS", "conditions": [],
  "pass_reasons": ["Blank check company — no operations or revenue",
                   "No identified target business",
                   "Score well below CONDITIONAL threshold",
                   "Sponsor economics favor insiders heavily"],
  "executive_summary": "$100M SPAC via Maxim Group on Nasdaq. No identified target. Sponsor holds 3.2M founder shares for $25K. WithumSmith+Brown as auditor (SPAC-standard). $750K working capital outside trust. Standard SPAC risks: trust redemptions, sponsor misalignment, 24-month window. PASS.",
  "business_overview": "Blank check company. No operations, no identified target. 100% of $100M in trust pending business combination. Sponsor BHAV Partners LLC controls structure.",
  "key_risks": ["No identified target", "Redemption dilution at BC vote",
                 "Sponsor incentive misalignment ($25K for 3.2M shares)",
                 "24-month deadline or liquidation", "Extension risk"],
  "related_party_flags": ["Sponsor (BHAV Partners LLC): 3.2M founder shares for $25K",
                           "Admin services $20K/month from Sponsor",
                           "Sponsor promissory note up to $500K at 0% interest"],
  "macro_sector_context": "SPAC market selective; Maxim Group mid-tier underwriter with SPAC history. No sector or target disclosed.",
  "deal_committee_narrative": "Standard mid-market SPAC. No differentiation vs peers. PASS pending target identification.",
  "is_amendment": True, "prior_memo_date": None,
  "amendment_changes_summary": "Amendment to original S-1. Updated underwriting agreement terms, capitalization, and founder share forfeiture structure. Core economics unchanged.",
  "accession_no": "0001213900-26-020436",
},

# ── 4. 21SHARES POLKADOT ETF ─────────────────────────────────────────────────
{
  "company_name": "21Shares Polkadot ETF",
  "proposed_ticker": "TDOT", "exchange": "Nasdaq",
  "sector": "Financial Services", "subsector": "Crypto ETF",
  "offering_size_usd_millions": 0.5, "offering_shares_millions": 0.02,
  "proposed_price_range": "$25.00 per share (initial seed)",
  "lead_underwriters": [], "underwriter_tier": None,
  "ipo_type": "ETF — Crypto Asset Grantor Trust",
  "filing_date": "2026-02-25",
  "filing_url": "https://www.sec.gov/Archives/edgar/data/2054247/000121390026020327/0001213900-26-020327-index.htm",
  "auditor": None, "auditor_flag": False,
  "financials": {
    "revenue_usd_millions": {"year_minus_2": None, "year_minus_1": None, "ttm": None},
    "revenue_growth_yoy_pct": None, "gross_margin_pct": None, "gross_margin_trend": "",
    "ebitda_usd_millions": None, "net_income_usd_millions": None,
    "cash_burn_quarterly_usd_millions": None, "cash_on_hand_pre_ipo_usd_millions": None,
    "estimated_runway_months_post_ipo": None, "total_debt_usd_millions": None,
    "stock_based_comp_pct_revenue": None, "rule_of_40_score": None,
    "nrr_pct": None, "cac_ltv_ratio": None,
    "ar_vs_revenue_growth_flag": False, "deferred_revenue_trend": "",
  },
  "ownership": {
    "secondary_shares_pct_offering": None, "founder_post_ipo_voting_control_pct": None,
    "dual_class_structure": False, "lock_up_days": None,
    "lock_up_flag": False, "insider_selling_flag": False,
  },
  "use_of_proceeds": {
    "growth_capital_pct": 100.0, "debt_repayment_pct": 0.0,
    "insider_liquidity_pct": 0.0, "general_corporate_pct": 0.0, "proceeds_flag": False,
  },
  "management": {
    "ceo_name": "Russell Barlow", "ceo_tenure_months": None,
    "cfo_name": None, "cfo_tenure_months": None, "board_independent_pct": None,
    "management_flags": ["Coinbase ecosystem dominates custody, staking, prime broker roles — concentration risk",
                         "Sponsor 'leanly staffed' per prospectus"],
  },
  "valuation": {
    "implied_ev_usd_millions": None, "ev_revenue_multiple": None,
    "sector_median_ev_revenue": None, "premium_to_sector_median_pct": None,
    "public_comps": [], "valuation_flag": False,
  },
  "red_flags": [
    "RF-07 VALUATION DISCONNECT — DOT security classification unsettled; Howey test unresolved",
    "RF-12 REGULATORY OVERHANG — SEC Crypto Task Force (Jan 2025) and evolving framework; XRP precedent",
    "RF-13 MARKET TIMING RISK — Single-asset crypto ETF; DOT price has seen >50% swings; zero diversification",
    "RF-14 CAPITAL STRUCTURE RISK — 28-day unbonding locks 40-70% of assets; redemption delays possible",
    "RF-15 PRODUCT CONCENTRATION — 100% single-asset exposure (DOT); no diversification",
    "RF-17 TECHNOLOGY OBSOLESCENCE — Polkadot network adoption lagging BTC/ETH; staking yield declining",
    "RF-09 RELATED PARTY RISK — Coinbase dominates custody + staking + prime broker + lending roles",
  ],
  "red_flag_count": 7, "going_concern": False,
  "scores": {"business_model_quality": 3, "financial_health_runway": 0,
              "market_competitive_position": 2, "management_governance": 4,
              "valuation_attractiveness": 2, "weighted_total": None},
  "recommendation": "PASS", "conditions": [],
  "pass_reasons": ["Extreme regulatory uncertainty on DOT security classification",
                   "Single-asset crypto ETF — zero diversification",
                   "28-day unbonding creates redemption liquidity risk",
                   "Coinbase concentration across custody, staking, prime brokerage",
                   "DOT network adoption lagging larger crypto assets",
                   "0.30% sponsor fee + 25% staking take erodes yield proposition"],
  "executive_summary": "21Shares Polkadot ETF (TDOT) is a Delaware grantor trust providing indirect DOT exposure on Nasdaq. Amendment No. 9. Initial seed $500K. Staking of 40-70% of holdings via Coinbase (28-day unbonding). Sponsor fee 0.30% + 25% of staking rewards. DOT security classification unresolved. Custody split Coinbase/BitGo (not FDIC-insured). Polkadot is smaller, less proven than BTC/ETH. PASS.",
  "business_overview": "Passive grantor trust holding DOT. Tracks CME CF Polkadot Dollar Reference Rate. Staking optional/discretionary. APs: Jane Street, Macquarie, Virtu. BNY Mellon as administrator. Coinbase Custody + BitGo as custodians. Quarterly staking distributions to shareholders.",
  "key_risks": ["DOT security classification risk (SEC enforcement could force liquidation)",
                 "Extreme DOT price volatility (>50% swings documented)",
                 "28-day unbonding creates redemption delays",
                 "Staking rewards uncertain and declining (inflation rate reduction Mar 2026)",
                 "Coinbase single-point-of-failure across multiple roles",
                 "Custody not FDIC-insured; private shared insurance",
                 "Regulatory framework still evolving (SEC Crypto Task Force)"],
  "related_party_flags": ["Sponsor: 21Shares US LLC (21co/FalconX subsidiary)",
                           "Coinbase: Custody + Staking + Prime Broker + Lender",
                           "BitGo Bank & Trust: Second custodian (federally chartered Dec 2025)",
                           "BNY Mellon: Administrator, Transfer Agent, Cash Custodian",
                           "CF Benchmarks: Pricing benchmark (UK-regulated)",
                           "Foreside Global Services: Marketing Agent"],
  "macro_sector_context": "Bitcoin spot ETFs approved 2024; ETH ETFs launched Jan 2024. Polkadot smaller, less battle-tested. DOT market cap ~$20B. Crypto-friendly administration but SEC enforcement precedent (XRP) shows rapid delisting risk.",
  "deal_committee_narrative": "This is a crypto pass-through vehicle, not an operating company. Fundamental risks: unresolved DOT security classification, single-asset concentration, Coinbase ecosystem lock-in, and declining staking yields. PASS.",
  "is_amendment": True, "prior_memo_date": None,
  "amendment_changes_summary": "Amendment No. 9. Prior amendments addressed DOT regulatory status, staking fee structure (15% to 25%), custody disclosures, and SEC comment resolution.",
  "accession_no": "0001213900-26-020327",
},

# ── 5. NEX NEO TECH INC. ──────────────────────────────────────────────────────
{
  "company_name": "Nex Neo Tech Inc.",
  "proposed_ticker": None, "exchange": "OTC",
  "sector": "Software / SaaS", "subsector": "Marketing & Content Creation APIs",
  "offering_size_usd_millions": 0.12, "offering_shares_millions": 5.0,
  "proposed_price_range": "$0.0245 per share",
  "lead_underwriters": [], "underwriter_tier": "Self-Underwritten",
  "ipo_type": "Direct", "filing_date": "2026-02-25",
  "filing_url": "https://www.sec.gov/Archives/edgar/data/2091438/000209143826000004/0002091438-26-000004-index.htm",
  "auditor": "Boladale Lawal & Co.", "auditor_flag": True,
  "financials": {
    "revenue_usd_millions": {"year_minus_2": None, "year_minus_1": None, "ttm": 0.0},
    "revenue_growth_yoy_pct": None, "gross_margin_pct": None, "gross_margin_trend": "N/A — no revenue",
    "ebitda_usd_millions": None, "net_income_usd_millions": -0.009,
    "cash_burn_quarterly_usd_millions": 0.009, "cash_on_hand_pre_ipo_usd_millions": 0.005,
    "estimated_runway_months_post_ipo": 7.0, "total_debt_usd_millions": 0.039,
    "stock_based_comp_pct_revenue": None, "rule_of_40_score": None,
    "nrr_pct": None, "cac_ltv_ratio": None,
    "ar_vs_revenue_growth_flag": False, "deferred_revenue_trend": "N/A",
  },
  "ownership": {
    "secondary_shares_pct_offering": 0.0, "founder_post_ipo_voting_control_pct": 32.4,
    "dual_class_structure": False, "lock_up_days": 180,
    "lock_up_flag": False, "insider_selling_flag": False,
  },
  "use_of_proceeds": {
    "growth_capital_pct": 45.0, "debt_repayment_pct": 0.0,
    "insider_liquidity_pct": 0.0, "general_corporate_pct": 9.0, "proceeds_flag": True,
  },
  "management": {
    "ceo_name": "Anastasiia Reish", "ceo_tenure_months": 1,
    "cfo_name": "Anastasiia Reish", "cfo_tenure_months": 1, "board_independent_pct": 0.0,
    "management_flags": ["CEO=CFO same person (age 26) — 1 month tenure",
                         "Non-US resident (Poland-based)",
                         "No prior public company experience",
                         "No employment agreements or key person insurance",
                         "Zero compensation to management"],
  },
  "valuation": {
    "implied_ev_usd_millions": 0.12, "ev_revenue_multiple": None,
    "sector_median_ev_revenue": None, "premium_to_sector_median_pct": None,
    "public_comps": ["Copy.ai", "Jasper", "Writesonic", "Grammarly", "Lumen5"],
    "valuation_flag": True,
  },
  "red_flags": [
    "RF-01 GOING CONCERN — Boladale Lawal & Co. issued substantial doubt opinion (Aug 31, 2025 and Nov 30, 2025)",
    "RF-05 RUNWAY RISK — $5,438 cash; $8,791/quarter burn; <7 months runway even at 50% funding",
    "RF-08 MANAGEMENT RED FLAGS — CEO/CFO same person, 1-month tenure, no public company experience, Poland-based",
    "RF-10 AUDIT ISSUES — Boladale Lawal & Co. (unknown small firm) issued going concern opinion",
    "RF-11 MARGIN RISK — Zero revenue after 11+ months; product launched Jan 2026; no monetization",
    "RF-14 CAPITAL STRUCTURE RISK — Negative stockholders equity (-$1,905); $39,485 founder loan outstanding",
    "RF-16 GEOGRAPHIC CONCENTRATION — Founder and ops in Poland; US judgment enforcement uncertain",
    "RF-17 TECHNOLOGY OBSOLESCENCE — OCR and AI writing market dominated by funded incumbents",
  ],
  "red_flag_count": 8, "going_concern": True,
  "scores": {"business_model_quality": 2, "financial_health_runway": 1,
              "market_competitive_position": 2, "management_governance": 1,
              "valuation_attractiveness": 1, "weighted_total": None},
  "recommendation": "PASS", "conditions": [],
  "pass_reasons": ["RF-01 Going concern — automatic PASS",
                   "Zero revenue after 11+ months of operation",
                   "Negative equity; $5,438 cash with $9K/quarter burn",
                   "1-month CEO tenure; sole person; no public company experience",
                   "Self-underwritten penny stock; no institutional backing"],
  "executive_summary": "Nex Neo Tech Inc. is a pre-revenue API startup founded Jan 14, 2025 in Poland. Image-to-Text API launched Jan 2026; Ad Copy Generator planned May-Aug 2026. Zero revenue; Q3 2025 loss $8,791; cash $5,438. Going concern from Boladale Lawal & Co. CEO/CFO same person (age 26, 1-month tenure). Competing against Copy.ai, Jasper, Grammarly with no capital or differentiation. Automatic PASS.",
  "business_overview": "Web-based APIs for marketing/content creators. Primary: Image-to-Text OCR (100+ languages). Planned: Blog Section, Ad Copy Generator. Subscription model: Basic/Standard/Premium tiers. No paying customers as of filing. Accessible at try.nexneoinc.com.",
  "key_risks": ["Going concern from auditor", "Zero revenue 11+ months in",
                 "Sub-7-month runway even at full raise", "Sole founder (age 26, 1 month tenure)",
                 "Intensely competitive market — Copy.ai, Jasper, Grammarly all better funded",
                 "Arbitrary pricing — NAV per share negative",
                 "No underwriter, no institutional validation"],
  "related_party_flags": ["Founder Anastasiia Reish: $39,485 interest-free loan to company",
                           "Founder acquired shares at $0.004 vs IPO at $0.0245 (6x premium)"],
  "macro_sector_context": "AI content/marketing tools growing but consolidating around well-funded platforms. OCR market commoditized. No differentiation or capital advantage for Nex Neo.",
  "deal_committee_narrative": "Pre-revenue startup with going concern, negative equity, and 1-month-tenure CEO/CFO. Automatic PASS.",
  "is_amendment": True, "prior_memo_date": None,
  "amendment_changes_summary": "Amendment 2. Updated financials through Nov 30, 2025. Disclosed Image-to-Text API launch (Jan 23, 2026). Going concern reinforced. Offering structure unchanged.",
  "accession_no": "0002091438-26-000004",
},

# ── 6. ILLUMINATION ACQUISITION CORP. I ───────────────────────────────────────
{
  "company_name": "Illumination Acquisition Corp. I",
  "proposed_ticker": None, "exchange": "Nasdaq",
  "sector": "SPAC", "subsector": "Blank Check Company",
  "offering_size_usd_millions": 200.0, "offering_shares_millions": 20.0,
  "proposed_price_range": "$10.00 per unit",
  "lead_underwriters": ["BTIG, LLC"],
  "underwriter_tier": "Mid-tier", "ipo_type": "Blank Check / SPAC",
  "filing_date": "2026-02-24",
  "filing_url": "https://www.sec.gov/Archives/edgar/data/2101135/000120677426000086/0001206774-26-000086-index.htm",
  "auditor": "WithumSmith+Brown PC", "auditor_flag": False,
  "financials": {
    "revenue_usd_millions": {"year_minus_2": None, "year_minus_1": None, "ttm": None},
    "revenue_growth_yoy_pct": None, "gross_margin_pct": None, "gross_margin_trend": "",
    "ebitda_usd_millions": None, "net_income_usd_millions": None,
    "cash_burn_quarterly_usd_millions": None, "cash_on_hand_pre_ipo_usd_millions": 200.0,
    "estimated_runway_months_post_ipo": None, "total_debt_usd_millions": 0.0,
    "stock_based_comp_pct_revenue": None, "rule_of_40_score": None,
    "nrr_pct": None, "cac_ltv_ratio": None,
    "ar_vs_revenue_growth_flag": False, "deferred_revenue_trend": "",
  },
  "ownership": {
    "secondary_shares_pct_offering": 0.0, "founder_post_ipo_voting_control_pct": 25.0,
    "dual_class_structure": True, "lock_up_days": 365,
    "lock_up_flag": True, "insider_selling_flag": False,
  },
  "use_of_proceeds": {
    "growth_capital_pct": None, "debt_repayment_pct": 0.0,
    "insider_liquidity_pct": 0.0, "general_corporate_pct": 100.0, "proceeds_flag": True,
  },
  "management": {
    "ceo_name": None, "ceo_tenure_months": None,
    "cfo_name": None, "cfo_tenure_months": None, "board_independent_pct": None,
    "management_flags": ["No identified target business",
                         "Sponsor holds 25% post-IPO at negligible cost",
                         "$20,000/month admin fee from day 1"],
  },
  "valuation": {
    "implied_ev_usd_millions": 200.0, "ev_revenue_multiple": None,
    "sector_median_ev_revenue": None, "premium_to_sector_median_pct": None,
    "public_comps": [], "valuation_flag": False,
  },
  "red_flags": [
    "RF-04 INSIDER LIQUIDITY — Sponsor 25% post-IPO at negligible cost; 1-year lock-up",
    "RF-06 GOVERNANCE RISK — Sponsor voting concentration; dual class structure",
    "RF-13 MARKET TIMING RISK — No identified target; 24-month window",
    "RF-14 CAPITAL STRUCTURE RISK — $7M deferred underwriting (3.5%) paid only on BC close",
  ],
  "red_flag_count": 4, "going_concern": False,
  "scores": {"business_model_quality": 1, "financial_health_runway": 4,
              "market_competitive_position": 1, "management_governance": 2,
              "valuation_attractiveness": 3, "weighted_total": None},
  "recommendation": "PASS", "conditions": [],
  "pass_reasons": ["Blank check company — no business to evaluate",
                   "No identified target or sector focus",
                   "Score well below CONDITIONAL threshold",
                   "Deferred underwriting reduces net proceeds to target"],
  "executive_summary": "$200M SPAC via BTIG on Nasdaq. No identified target. Sponsor 25% post-IPO stake. $20K/month admin fee. WithumSmith+Brown as auditor. Standard SPAC structure with 24-month window. PASS.",
  "business_overview": "Blank check Cayman Islands company. No operations, no identified target. $200M in trust. 24-month window for business combination.",
  "key_risks": ["No identified target — binary outcome",
                 "Redemption dilution at business combination",
                 "24-month deadline pressure",
                 "Sponsor conflict — low-cost founder stake",
                 "$7M deferred commission reduces target value"],
  "related_party_flags": ["Sponsor (Illumination Acquisition 1 Sponsor LLC): 25% post-IPO stake",
                           "Admin services $20K/month",
                           "Sponsor loans up to $250K at 0% interest"],
  "macro_sector_context": "SPAC market active but facing redemption scrutiny. BTIG mid-tier underwriter. No sector or target disclosed.",
  "deal_committee_narrative": "Standard SPAC. No differentiation. PASS pending target identification.",
  "is_amendment": True, "prior_memo_date": None, "amendment_changes_summary": None,
  "accession_no": "0001206774-26-000086",
},

# ── 7. AMAZE HOLDINGS, INC. ───────────────────────────────────────────────────
{
  "company_name": "Amaze Holdings, Inc.",
  "proposed_ticker": "AMZE", "exchange": "NYSE American",
  "sector": "Technology / E-Commerce", "subsector": "Digital Commerce Platform",
  "offering_size_usd_millions": 25.0, "offering_shares_millions": 50.0,
  "proposed_price_range": "$0.20 floor (95% of VWAP)",
  "lead_underwriters": [], "underwriter_tier": "None — Secondary Offering",
  "ipo_type": "Secondary Offering (Shelf Registration / Equity Line)",
  "filing_date": "2026-02-24",
  "filing_url": "https://www.sec.gov/Archives/edgar/data/1880343/000149315226007891/0001493152-26-007891-index.htm",
  "auditor": None, "auditor_flag": True,
  "financials": {
    "revenue_usd_millions": {"year_minus_2": None, "year_minus_1": None, "ttm": None},
    "revenue_growth_yoy_pct": None, "gross_margin_pct": None, "gross_margin_trend": "",
    "ebitda_usd_millions": None, "net_income_usd_millions": -12.3,
    "cash_burn_quarterly_usd_millions": None, "cash_on_hand_pre_ipo_usd_millions": None,
    "estimated_runway_months_post_ipo": None, "total_debt_usd_millions": 6.3,
    "stock_based_comp_pct_revenue": None, "rule_of_40_score": None,
    "nrr_pct": None, "cac_ltv_ratio": None,
    "ar_vs_revenue_growth_flag": False, "deferred_revenue_trend": "",
  },
  "ownership": {
    "secondary_shares_pct_offering": 100.0, "founder_post_ipo_voting_control_pct": None,
    "dual_class_structure": False, "lock_up_days": None,
    "lock_up_flag": False, "insider_selling_flag": False,
  },
  "use_of_proceeds": {
    "growth_capital_pct": 100.0, "debt_repayment_pct": 0.0,
    "insider_liquidity_pct": 0.0, "general_corporate_pct": 0.0, "proceeds_flag": False,
  },
  "management": {
    "ceo_name": "Aaron Day", "ceo_tenure_months": None,
    "cfo_name": "Joel Krutz", "cfo_tenure_months": 2, "board_independent_pct": None,
    "management_flags": ["New CFO hired January 5, 2026 (2 months tenure)",
                         "Material weaknesses in internal controls since 2021 — unresolved",
                         "Most team members lack public company experience"],
  },
  "valuation": {
    "implied_ev_usd_millions": None, "ev_revenue_multiple": None,
    "sector_median_ev_revenue": None, "premium_to_sector_median_pct": None,
    "public_comps": [], "valuation_flag": False,
  },
  "red_flags": [
    "RF-01 GOING CONCERN — Auditor issued substantial doubt on ability to continue as going concern",
    "RF-03 REVENUE QUALITY — No revenue data disclosed; $12.3M loss in 9 months 2025",
    "RF-04 INSIDER LIQUIDITY GRAB — 100% secondary offering; company receives no proceeds",
    "RF-05 RUNWAY RISK — $12.3M loss in 9 months; $6.3M debt; no disclosed cash",
    "RF-08 MANAGEMENT RED FLAGS — CFO hired Jan 2026 (2 months tenure); prior CEO resigned Dec 2025",
    "RF-10 AUDIT ISSUES — Material weaknesses in internal controls since 2021 — unresolved",
    "RF-12 REGULATORY OVERHANG — NYSE American listing at risk; stock at $0.34 post 1-for-23 reverse split",
    "RF-14 CAPITAL STRUCTURE RISK — $97M goodwill from Amaze acquisition faces impairment; $6.3M debt",
  ],
  "red_flag_count": 8, "going_concern": True,
  "scores": {"business_model_quality": 3, "financial_health_runway": 2,
              "market_competitive_position": 3, "management_governance": 2,
              "valuation_attractiveness": 4, "weighted_total": None},
  "recommendation": "PASS", "conditions": [],
  "pass_reasons": ["RF-01 Going concern — automatic PASS",
                   "100% secondary — company receives no capital",
                   "$12.3M loss in 9 months; $6.3M debt; $97M goodwill at impairment risk",
                   "Material internal control weaknesses unresolved since 2021",
                   "Stock below $1 minimum bid; delisting risk",
                   "CEO turnover Dec 2025; CFO hired Jan 2026"],
  "executive_summary": "Amaze Holdings (formerly Fresh Vine Wine, now digital commerce + wine) is a secondary offering (resale registration) by C/M Capital Master Fund LP — company receives no proceeds. Going concern from auditor. $12.3M loss in 9 months 2025. $97M goodwill from Amaze Software acquisition (Mar 2025) at impairment risk. Stock at $0.34 post 1-for-23 reverse split; below $1 Nasdaq minimum bid. Unresolved material control weaknesses since 2021. Non-binding equity line at $0.20 floor. PASS.",
  "business_overview": "Dual-segment: (1) creator e-commerce platform (Amaze Software, acquired Mar 2025) and (2) low-carb wine (Fresh Vine, <10% of revenues). Combined entity 11 months post-acquisition. Prior CEO resigned Dec 2025; new CFO Jan 2026.",
  "key_risks": ["Going concern", "100% secondary with no capital raise",
                 "$12.3M loss in 9 months with no disclosed path to profitability",
                 "$97M goodwill impairment risk", "Unresolved material weaknesses since 2021",
                 "Nasdaq delisting risk", "Management turmoil (CEO/CFO turnover)",
                 "Non-binding equity line (can be withdrawn at any time)"],
  "related_party_flags": ["C/M Capital Master Fund LP (Selling Stockholder) — non-binding $25M equity line",
                           "CEO Aaron Day", "CFO Joel Krutz (hired Jan 5, 2026)"],
  "macro_sector_context": "Creator economy platforms face CAC/LTV pressure. Wine direct-to-consumer market saturated. Combined entity has no proven synergies post-acquisition.",
  "deal_committee_narrative": "Distressed micro-cap secondary with going concern, management turmoil, unresolved internal controls, and non-binding equity line. Company receives zero capital. PASS.",
  "is_amendment": True, "prior_memo_date": None,
  "amendment_changes_summary": "Pre-Effective Amendment No. 1. Reduced committed equity from $35M to $25M. Updated share count (50M registered) and dilution tables as of Feb 6, 2026.",
  "accession_no": "0001493152-26-007891",
},

# ── 8. NETCAPITAL INC. ────────────────────────────────────────────────────────
{
  "company_name": "Netcapital Inc.",
  "proposed_ticker": "NCPL", "exchange": "Nasdaq Capital Market",
  "sector": "Financial Services", "subsector": "Fintech — Regulation Crowdfunding Portal",
  "offering_size_usd_millions": 0.0, "offering_shares_millions": 1.88,
  "proposed_price_range": "N/A — Secondary Resale Registration",
  "lead_underwriters": [], "underwriter_tier": "N/A",
  "ipo_type": "Secondary Offering — Resale Registration (S-1/A Amendment No. 3)",
  "filing_date": "2026-02-24",
  "filing_url": "https://www.sec.gov/Archives/edgar/data/1414767/000149315226007888/0001493152-26-007888-index.htm",
  "auditor": None, "auditor_flag": False,
  "financials": {
    "revenue_usd_millions": {"year_minus_2": 4.95, "year_minus_1": 0.87, "ttm": 0.24},
    "revenue_growth_yoy_pct": -82.4, "gross_margin_pct": 95.4,
    "gross_margin_trend": "Stable but off a collapsing revenue base",
    "ebitda_usd_millions": None, "net_income_usd_millions": -5.77,
    "cash_burn_quarterly_usd_millions": 2.89, "cash_on_hand_pre_ipo_usd_millions": 0.79,
    "estimated_runway_months_post_ipo": 3.0, "total_debt_usd_millions": None,
    "stock_based_comp_pct_revenue": None, "rule_of_40_score": None,
    "nrr_pct": None, "cac_ltv_ratio": None,
    "ar_vs_revenue_growth_flag": False, "deferred_revenue_trend": "Declining",
  },
  "ownership": {
    "secondary_shares_pct_offering": 100.0, "founder_post_ipo_voting_control_pct": None,
    "dual_class_structure": False, "lock_up_days": None,
    "lock_up_flag": False, "insider_selling_flag": True,
  },
  "use_of_proceeds": {
    "growth_capital_pct": None, "debt_repayment_pct": None,
    "insider_liquidity_pct": 100.0, "general_corporate_pct": 0.0, "proceeds_flag": True,
  },
  "management": {
    "ceo_name": "Rich Wheeless", "ceo_tenure_months": 3,
    "cfo_name": "Coreen Kraysler", "cfo_tenure_months": None, "board_independent_pct": None,
    "management_flags": ["CEO appointed Dec 7, 2025 (3 months tenure); prior CEO resigned",
                         "Founder Jason Frishman owns 29% of licensed tech platform (related party)",
                         "Limited board disclosure"],
  },
  "valuation": {
    "implied_ev_usd_millions": 4.21, "ev_revenue_multiple": None,
    "sector_median_ev_revenue": None, "premium_to_sector_median_pct": None,
    "public_comps": ["StartEngine Crowdfunding Inc.", "Wefunder Inc.", "Republic Core LLC"],
    "valuation_flag": True,
  },
  "red_flags": [
    "RF-01 GOING CONCERN — Auditor substantial doubt for 12 months (FY25 opinion)",
    "RF-03 REVENUE QUALITY — Revenue collapsed 82% YoY ($4.95M → $869K); H1 FY26 down 23% further",
    "RF-04 INSIDER LIQUIDITY GRAB — 100% secondary; investors from Jun-Jul 2025 placements at $7.00/$4.675 seeking exit at ~$0.54",
    "RF-05 RUNWAY RISK — $792K cash; $2.89M/quarter burn; ~3-month runway",
    "RF-08 MANAGEMENT RED FLAGS — CEO 3 months tenure; prior CEO forced resignation",
    "RF-10 AUDIT ISSUES — Material control weaknesses; Nasdaq minimum bid violation (cure deadline Aug 3, 2026)",
    "RF-12 REGULATORY OVERHANG — Nasdaq delisting risk; below $1.00 minimum bid since at least Feb 4, 2026",
    "RF-13 MARKET TIMING RISK — Platform adoption collapse: new offerings down 73% YoY",
  ],
  "red_flag_count": 8, "going_concern": True,
  "scores": {"business_model_quality": 2, "financial_health_runway": 1,
              "market_competitive_position": 2, "management_governance": 3,
              "valuation_attractiveness": 1, "weighted_total": None},
  "recommendation": "PASS", "conditions": [],
  "pass_reasons": ["RF-01 Going concern — automatic PASS",
                   "Revenue -82% YoY; $792K cash; 3-month runway",
                   "Nasdaq minimum bid violation with Aug 2026 cure deadline",
                   "100% secondary — company receives no capital",
                   "Core platform adoption collapsing (73% YoY decline in new offerings)"],
  "executive_summary": "Netcapital (NCPL) is a distressed Reg CF crowdfunding portal. This S-1/A No. 3 is a secondary resale of 1.88M shares from Jun-Jul 2025 placements (no company proceeds). Revenue collapsed 82% to $869K after eliminating consulting equity fees. $792K cash; $2.89M/quarter burn; ~3-month runway. Auditor issued going concern. Stock below $1 minimum bid (delisting deadline Aug 3, 2026). CEO changed Dec 2025. Platform adoption down 73% YoY. PASS.",
  "business_overview": "Reg CF portal (Netcapital Funding Portal) + FINRA broker-dealer (Nov 2024) + advisory. Fees: $5K listing + 4.9% success + 1% equity. 87 portfolio companies; $5.86M FMV; 12 written to $0. Terminated Templum ATS (Sept 2025). Pivoting to blockchain/RWAs with Horizon Globex — zero revenue from pivot.",
  "key_risks": ["Going concern", "$792K cash; 3-month runway",
                 "Nasdaq delisting (Aug 3, 2026 cure deadline)",
                 "Revenue model broken — consulting equity eliminated, not replaced",
                 "Platform adoption collapsing",
                 "CEO 3-month tenure; forced prior-CEO resignation",
                 "Unproven blockchain/RWA pivot",
                 "Related party: 29% of tech licensed from founder ($95K/year)"],
  "related_party_flags": ["Founder Jason Frishman (29% of Netcapital Systems LLC) — $95K annual tech license",
                           "Cecilia Lenk (board member) CEO of Deuce Drone LLC — $2.35M investment written off"],
  "macro_sector_context": "Reg CF market growing but consolidating; StartEngine, Wefunder, Republic gaining share. Netcapital losing platform adoption. Blockchain/RWA pivot dependent on unresolved regulatory framework.",
  "deal_committee_narrative": "Distressed fintech portal with going concern, collapsing revenue, 3-month runway, and Nasdaq delisting risk. 100% secondary. PASS.",
  "is_amendment": True, "prior_memo_date": None,
  "amendment_changes_summary": "Amendment No. 3. Updated financials through Oct 31, 2025. Disclosed going concern, Nasdaq warning, CEO transition, Rivetz/Iverson acquisitions, and Templum termination.",
  "accession_no": "0001493152-26-007888",
},

# ── 9. GALAXYEDGE ACQUISITION CORP ───────────────────────────────────────────
{
  "company_name": "GalaxyEdge Acquisition Corporation",
  "proposed_ticker": "GLED", "exchange": "NYSE",
  "sector": "SPAC", "subsector": "Blank Check Company",
  "offering_size_usd_millions": 100.0, "offering_shares_millions": 10.0,
  "proposed_price_range": "$10.00 per unit",
  "lead_underwriters": ["Polaris Advisory Partners"],
  "underwriter_tier": "Mid-tier", "ipo_type": "SPAC IPO",
  "filing_date": "2026-02-24",
  "filing_url": "https://www.sec.gov/Archives/edgar/data/2091484/000182912626001608/0001829126-26-001608-index.htm",
  "auditor": "Simon & Edward, LLP", "auditor_flag": False,
  "financials": {
    "revenue_usd_millions": {"year_minus_2": None, "year_minus_1": None, "ttm": None},
    "revenue_growth_yoy_pct": None, "gross_margin_pct": None, "gross_margin_trend": "",
    "ebitda_usd_millions": None, "net_income_usd_millions": None,
    "cash_burn_quarterly_usd_millions": None, "cash_on_hand_pre_ipo_usd_millions": 100.0,
    "estimated_runway_months_post_ipo": None, "total_debt_usd_millions": None,
    "stock_based_comp_pct_revenue": None, "rule_of_40_score": None,
    "nrr_pct": None, "cac_ltv_ratio": None,
    "ar_vs_revenue_growth_flag": False, "deferred_revenue_trend": "",
  },
  "ownership": {
    "secondary_shares_pct_offering": 0.0, "founder_post_ipo_voting_control_pct": 25.9,
    "dual_class_structure": False, "lock_up_days": 180,
    "lock_up_flag": True, "insider_selling_flag": False,
  },
  "use_of_proceeds": {
    "growth_capital_pct": None, "debt_repayment_pct": None,
    "insider_liquidity_pct": 0.0, "general_corporate_pct": 100.0, "proceeds_flag": True,
  },
  "management": {
    "ceo_name": "Ping Zhang", "ceo_tenure_months": 5,
    "cfo_name": "Ping Zhang", "cfo_tenure_months": 5, "board_independent_pct": 75.0,
    "management_flags": ["CEO=CFO same person",
                         "Significant PRC/China ties — CSRC overseas listing approval risk",
                         "CEO simultaneously on boards of multiple other SPACs",
                         "No prior blank check company experience",
                         "Sponsor acquired 4.025M founder shares for $25K ($0.0062/share)"],
  },
  "valuation": {
    "implied_ev_usd_millions": 100.0, "ev_revenue_multiple": None,
    "sector_median_ev_revenue": None, "premium_to_sector_median_pct": None,
    "public_comps": [], "valuation_flag": False,
  },
  "red_flags": [
    "RF-04 INSIDER LIQUIDITY — Sponsor 4.025M founder shares for $25K ($0.0062/share); extreme dilution",
    "RF-06 GOVERNANCE RISK — CEO=CFO; board member on 6+ other SPACs simultaneously; PRC regulatory risk",
    "RF-09 RELATED PARTY RISK — $700K sponsor loan; $15K/month admin fee",
    "RF-12 REGULATORY OVERHANG — CSRC approval unclear for overseas listing; PRC political risk",
    "RF-13 MARKET TIMING RISK — No identified target; 21-month window; broad EV range $180M-$1B",
  ],
  "red_flag_count": 5, "going_concern": False,
  "scores": {"business_model_quality": 1, "financial_health_runway": 4,
              "market_competitive_position": 1, "management_governance": 2,
              "valuation_attractiveness": 3, "weighted_total": None},
  "recommendation": "PASS", "conditions": [],
  "pass_reasons": ["Blank check company — no business to evaluate",
                   "No identified target; PRC regulatory risk adds complexity",
                   "CEO/CFO same person serving on 6+ other SPACs",
                   "Sponsor $25K for 25.9% stake — severe misalignment",
                   "Score well below CONDITIONAL threshold"],
  "executive_summary": "$100M SPAC via Polaris Advisory Partners on NYSE. No identified target. Sponsor Equinox Capital Solutions paid $25K for 4.025M founder shares (25.9% post-IPO). CEO Ping Zhang also serves as CFO and sits on 6+ other SPACs simultaneously. Significant PRC ties create CSRC overseas listing regulatory risk. 21-month window. PASS.",
  "business_overview": "Blank check Cayman Islands company, formed Sept 2025. No operations. $100M in trust. Broad target criteria: EV $180M-$1B, any sector/geography. Strong PRC bias due to management connections.",
  "key_risks": ["No identified target", "PRC regulatory uncertainty (CSRC approval risk)",
                 "CEO on 6+ other SPACs — bandwidth concerns",
                 "Sponsor $25K for 25.9% stake — perverse incentives",
                 "21-month deadline",
                 "No prior blank check experience for management"],
  "related_party_flags": ["Sponsor (Equinox Capital Solutions): 4.025M shares for $25K",
                           "$700K sponsor loan for offering expenses",
                           "$15K/month admin fee",
                           "CEO Ping Zhang: concurrent board member on Quantumsphere, Quartzsea, Pelican, Yotta, Quetta, QuasarEdge SPACs"],
  "macro_sector_context": "PRC-focused SPACs face CSRC regulatory headwinds and VIE structure concerns. NYSE listing requirements impose 80% asset test and 21-month deadline. Investor sentiment toward SPAC structures mixed.",
  "deal_committee_narrative": "SPAC with significant governance concerns: CEO/CFO same person; 6+ concurrent SPAC roles; $25K for 25.9% of entity; PRC regulatory overhang. PASS.",
  "is_amendment": True, "prior_memo_date": None,
  "amendment_changes_summary": "Amendment No. 3. Updated management bios, risk factors, and disclosures per SEC comment review.",
  "accession_no": "0001829126-26-001608",
},

# ── 10. BLUE WATER ACQUISITION CORP. IV ──────────────────────────────────────
{
  "company_name": "Blue Water Acquisition Corp. IV",
  "proposed_ticker": "BWACU", "exchange": "NYSE",
  "sector": "SPAC", "subsector": "Blank Check Company",
  "offering_size_usd_millions": 125.0, "offering_shares_millions": 12.5,
  "proposed_price_range": "$10.00 per unit",
  "lead_underwriters": ["BTIG, LLC"],
  "underwriter_tier": "Mid-tier", "ipo_type": "SPAC IPO",
  "filing_date": "2026-02-24",
  "filing_url": "https://www.sec.gov/Archives/edgar/data/2082847/000149315226007866/0001493152-26-007866-index.htm",
  "auditor": "Elliott Davis, PLLC", "auditor_flag": False,
  "financials": {
    "revenue_usd_millions": {"year_minus_2": None, "year_minus_1": None, "ttm": None},
    "revenue_growth_yoy_pct": None, "gross_margin_pct": None, "gross_margin_trend": "",
    "ebitda_usd_millions": None, "net_income_usd_millions": None,
    "cash_burn_quarterly_usd_millions": None, "cash_on_hand_pre_ipo_usd_millions": 125.0,
    "estimated_runway_months_post_ipo": None, "total_debt_usd_millions": 0.0,
    "stock_based_comp_pct_revenue": None, "rule_of_40_score": None,
    "nrr_pct": None, "cac_ltv_ratio": None,
    "ar_vs_revenue_growth_flag": False, "deferred_revenue_trend": "",
  },
  "ownership": {
    "secondary_shares_pct_offering": 0.0, "founder_post_ipo_voting_control_pct": 25.0,
    "dual_class_structure": True, "lock_up_days": 365,
    "lock_up_flag": True, "insider_selling_flag": False,
  },
  "use_of_proceeds": {
    "growth_capital_pct": 80.0, "debt_repayment_pct": 0.0,
    "insider_liquidity_pct": 0.0, "general_corporate_pct": 20.0, "proceeds_flag": True,
  },
  "management": {
    "ceo_name": None, "ceo_tenure_months": None,
    "cfo_name": None, "cfo_tenure_months": None, "board_independent_pct": None,
    "management_flags": ["No identified target business",
                         "Sponsor formed Aug 1, 2025 — new entity with no track record",
                         "$10K/month admin fee from sponsor",
                         "Sponsor up to $300K bridge financing"],
  },
  "valuation": {
    "implied_ev_usd_millions": 125.0, "ev_revenue_multiple": None,
    "sector_median_ev_revenue": None, "premium_to_sector_median_pct": None,
    "public_comps": [], "valuation_flag": False,
  },
  "red_flags": [
    "RF-04 INSIDER LIQUIDITY — Sponsor 4.79M founder shares at negligible cost; 25% post-IPO",
    "RF-05 RUNWAY RISK — Only $1M working capital outside trust; $10K/month admin fee",
    "RF-06 GOVERNANCE RISK — Dual class; sponsor voting concentration; 1-year lock-up",
    "RF-13 MARKET TIMING RISK — No identified target; sponsor newly formed Aug 2025 with no track record",
    "RF-14 CAPITAL STRUCTURE RISK — $4.375M deferred underwriting (3.5%) + $1.03M option; warrant overhang 10.5M warrants",
  ],
  "red_flag_count": 5, "going_concern": False,
  "scores": {"business_model_quality": 2, "financial_health_runway": 4,
              "market_competitive_position": 0, "management_governance": 3,
              "valuation_attractiveness": 4, "weighted_total": None},
  "recommendation": "PASS", "conditions": [],
  "pass_reasons": ["Blank check company — no business to evaluate",
                   "No identified target or sector focus",
                   "Sponsor newly formed Aug 2025 — no track record",
                   "Score well below CONDITIONAL threshold",
                   "10.5M warrant overhang creates significant dilution"],
  "executive_summary": "$125M SPAC via BTIG on NYSE. No identified target. Sponsor (Blue Water Acquisition IV LLC, formed Aug 2025) holds 4.79M founder shares (25% post-IPO). $4.375M deferred underwriting. Elliott Davis as auditor. 24-month window extendable +12 months. PASS.",
  "business_overview": "Blank check Cayman Islands company. No operations, no identified target. $125M in trust. Any sector/geography. 24-month window with optional 1-year extension.",
  "key_risks": ["No identified target",
                 "Sponsor newly formed — no track record of SPAC completion",
                 "24-month deadline + extension risk",
                 "10.5M warrants (6.25M public + 4.25M private) at $11.50 strike",
                 "Redemption dilution at BC vote",
                 "Deferred underwriting reduces net proceeds to target"],
  "related_party_flags": ["Sponsor (Blue Water Acquisition IV LLC): 4.79M shares at nominal cost",
                           "Admin services $10K/month",
                           "Sponsor bridge loans up to $300K",
                           "BTIG: 125K private placement units + deferred underwriting"],
  "macro_sector_context": "SPAC market faces redemption scrutiny and deal quality concerns post-2021 peak. BTIG has mid-tier SPAC credibility. Sponsor has no prior SPAC track record.",
  "deal_committee_narrative": "Standard SPAC with new sponsor, no target, no differentiation. Warrant overhang substantial. PASS.",
  "is_amendment": True, "prior_memo_date": None, "amendment_changes_summary": None,
  "accession_no": "0001493152-26-007866",
},

]  # end MEMOS list

# ── SAVE & INDEX ──────────────────────────────────────────────────────────────
memos_out = []
for m in MEMOS:
    m = fix_scores(m)
    fname = DATE_DIR / f"{slug(m['company_name'])}.json"
    with open(fname, "w") as f:
        json.dump(m, f, indent=2)
    rec = m["recommendation"]
    score = m["scores"]["weighted_total"]
    gc = " [GC]" if m["going_concern"] else ""
    amd = " [AMD]" if m["is_amendment"] else ""
    print(f"  {rec:<12} {score:5.1f}/100{gc}{amd}  {m['company_name']}")
    memos_out.append(m)

# Daily index
index = {
    "run_date":          RUN_DATE,
    "run_timestamp":     datetime.now(PACIFIC).isoformat(),
    "total_filings":     len(memos_out),
    "underwrite_count":  sum(1 for m in memos_out if m["recommendation"] == "UNDERWRITE"),
    "conditional_count": sum(1 for m in memos_out if m["recommendation"] == "CONDITIONAL"),
    "pass_count":        sum(1 for m in memos_out if m["recommendation"] == "PASS"),
    "error_count":       0,
    "companies": [
        {
            "company_name":               m["company_name"],
            "proposed_ticker":            m["proposed_ticker"],
            "sector":                     m["sector"],
            "offering_size_usd_millions": m["offering_size_usd_millions"],
            "recommendation":             m["recommendation"],
            "score":                      m["scores"]["weighted_total"],
            "red_flag_count":             m["red_flag_count"],
            "going_concern":              m["going_concern"],
            "is_amendment":               m["is_amendment"],
        }
        for m in sorted(memos_out, key=lambda x: -(x["scores"]["weighted_total"] or 0))
    ],
}
with open(DATE_DIR / "_index.json", "w") as f:
    json.dump(index, f, indent=2)

# Manifest
manifest_path = DATA_DIR / "_manifest.json"
manifest = json.loads(manifest_path.read_text()) if manifest_path.exists() else {"dates": []}
if RUN_DATE not in manifest["dates"]:
    manifest["dates"].append(RUN_DATE)
    manifest["dates"].sort(reverse=True)
manifest["last_updated"] = datetime.now(PACIFIC).isoformat()
manifest_path.write_text(json.dumps(manifest, indent=2))

print(f"\n  {len(memos_out)} memos saved → {DATE_DIR}")
print(f"  UNDERWRITE: {index['underwrite_count']}  CONDITIONAL: {index['conditional_count']}  PASS: {index['pass_count']}")
